[package]
name = "string-interner"
version = "0.8.0"
authors = ["Robbepop"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/robbepop/string-interner"
documentation = "https://docs.rs/string-interner"
keywords = ["interner", "intern", "string", "str", "symbol"]
description = """An efficient string interning data structure with minimal memory footprint
and fast access to the underlying strings.
"""
categories = ["data-structures"]
edition = "2018"

[dependencies]
cfg-if = "0.1.10"
serde = { version = "1.0", optional = true }

[dev-dependencies]
fnv = "1.0"         # Required bench tests.
serde_json = "1.0"  # Required for testing the serde implementation.
lazy_static = "1.0" # Required for benches.
criterion = "0.3.1" # Required for benches.

[[bench]]
name = "bench"
harness = false

[features]
default       = ["std", "serde-1"]
std           = []
bench         = ["std"]
serde-1 = ["serde"]

[badges]
travis-ci = { repository = "Robbepop/string-interner" }
appveyor = { repository = "Robbepop/string-interner", branch = "master", service = "github" }
